### ISSUE TITLE
A tutor should be able to hide their grades

### ISSUE THREAD

**Issue by jlvivero** [TutorFox/TutorFox#31]
The button to hide your grades is already there, but nothing is implemented

**Comment by A-deLuna** [comment]
1st extend models/User.js and add a showGrades property.

for src/TutorPage.js
in line 13 add showGrades property to state
in 48 set that state in the get request
then in line 127 and 130 change this.props.showGrades to this.state.showGrades

**Comment by A-deLuna** [comment]
for src/TutorPanel.js
in line 37 change showGrades={true} to showGrades={tutor.showGrades}

**Comment by jlvivero** [comment]
You mean src/Tutors.js instead of TutorPanel I believe

Also:  
- Modifying Registration.js so that the POST will include showGrades.  
- In the backend I will add to the user/classes/id the showGrades variable as well as part of the post

**Comment by jlvivero** [comment]
Also, modifying Registration.js so that the POST will include showGrades.

In the backend I will add to the user/classes/id the showGrades variable as well as part of the post

**Comment by A-deLuna** [comment]
I mean both, grades should be hiddable in TutorPanel and TutorPage

**Comment by A-deLuna** [comment]
That's right Tutors.js!
