### ISSUE TITLE
Tutors should be ordered by number of likes

### ISSUE THREAD

**Issue by jlvivero** [TutorFox/TutorFox#34]

**Comment by A-deLuna** [comment]
theres some magic to be done in routes/search.js
i believe theres a way to have values sorted when making a query in mongo, let's look that up in the mongo docs

**Comment by jlvivero** [comment]
http://mongoosejs.com/docs/queries.html

in here you can see that you can chain queries by making a query that's executed at a later time
var query = Person.findOne({ 'name.last': 'Ghost' });
query.select('name occupation');

in our case we'd keep the original query and would add:  
query.sort('-likes') or so it would be if we had likes as a number.
In reality there's no total count of likes in our database, so we can't really sort them properly like this

My suggestion is adding a likeCount to the database that is used only when using the search function (the rest of the like functions remains the same)

**Comment by A-deLuna** [comment]
fixed in #47
