### ISSUE TITLE
Remove unecessary alerts in the codebase

### ISSUE THREAD

**Issue by A-deLuna** [TutorFox/TutorFox#39]
grep alert -rn src/ 
src/TutorPage.js:95:    alert('button clicked' + this.props.id);
src/TutorPage.js:102:        alert('tutor notified');
src/TutorPage.js:108:    alert('button comment');
src/TutorPage.js:117:        alert('comment sent');

**Comment by jlvivero** [comment]
ill take this

Gonna leave tutor notified and comment sent and remove the other two
(unless anyone wants to remove those tell me and ill just remove them)
