### ISSUE TITLE
Que hacemos con About y Contact us ? 

### ISSUE THREAD

**Issue by A-deLuna** [TutorFox/TutorFox#45]
+1 a quitarlos

**Comment by jlvivero** [comment]
nadamas a poner nuestros correos abajo como un footer, quitar el contact us, y quitar el about us

**Comment by A-deLuna** [comment]
yeah lo mas sencillo sera nomas quitarlos

**Comment by A-deLuna** [comment]
esta en src/GeneralNavbar.js creo

**Comment by Just-Ic3** [comment]
Elimine ambas secciones de la Navbar, pero no estoy muy de acuerdo con la idea del footer, a menos que sea nomas en la frontpage, se me hace que estan medio feos los correos hasta abajo en todas partes.
